
apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  labels:
    env: prod
    dc: US
spec:
  containers:
  - name: "mycon1"
    image: "vimal13/apache-webserver-php"
    volumeMounts:
    - name: web-vol1
      mountPath: /var/www/html
  volumes:
  - name: web-vol1
    persistentVolumeClaim:
      claimName:  mypvc1